class ZCL_ZPURCHASE_ORDER_01_DPC_EXT definition
  public
  inheriting from ZCL_ZPURCHASE_ORDER_01_DPC
  create public .

public section.
protected section.

  methods PURCHASEORDERHEA_GET_ENTITYSET
    redefinition .
  methods PURCHASEORDERITE_GET_ENTITYSET
    redefinition .
private section.
ENDCLASS.



CLASS ZCL_ZPURCHASE_ORDER_01_DPC_EXT IMPLEMENTATION.


METHOD PURCHASEORDERHEA_GET_ENTITYSET.

  DATA: LS_HEADER  TYPE ZCL_ZPURCHASE_ORDER_01_MPC=>TS_PURCHASEORDERHEADER,
        LV_BUKRS   TYPE EKKO-BUKRS,
        LV_EBELN   TYPE EKKO-EBELN,
        LV_EKORG   TYPE EKKO-EKORG,
        LV_EKGRP   TYPE EKKO-EKGRP,
        LV_BEDAT_F TYPE EKKO-BEDAT,
        LV_BEDAT_T TYPE EKKO-BEDAT.

  "--- Đọc filter từ URL ---
  LOOP AT IT_FILTER_SELECT_OPTIONS INTO DATA(LS_SEL).
    CASE LS_SEL-PROPERTY.
      WHEN 'Bukrs'. LV_BUKRS   = LS_SEL-SELECT_OPTIONS[ 1 ]-LOW.
      WHEN 'Ebeln'. LV_EBELN   = LS_SEL-SELECT_OPTIONS[ 1 ]-LOW.
      WHEN 'Ekorg'. LV_EKORG   = LS_SEL-SELECT_OPTIONS[ 1 ]-LOW.
      WHEN 'Ekgrp'. LV_EKGRP   = LS_SEL-SELECT_OPTIONS[ 1 ]-LOW.
      WHEN 'Bedat'.
        LV_BEDAT_F = LS_SEL-SELECT_OPTIONS[ 1 ]-LOW.
        LV_BEDAT_T = LS_SEL-SELECT_OPTIONS[ 1 ]-HIGH.
    ENDCASE.
  ENDLOOP.

  "--- Validate Company Code ---
  IF LV_BUKRS IS NOT INITIAL.
    SELECT SINGLE BUKRS FROM T001
      INTO @DATA(LV_CHK)
      WHERE BUKRS = @LV_BUKRS.
    IF SY-SUBRC <> 0.
      RAISE EXCEPTION TYPE /IWBEP/CX_MGW_BUSI_EXCEPTION
        EXPORTING
          MESSAGE = |Company Code '{ LV_BUKRS }' does not exist.|.
    ENDIF.
  ENDIF.

  "--- Validate Purchasing Organization ---
  IF LV_EKORG IS NOT INITIAL.
    SELECT SINGLE EKORG FROM T024E
      INTO @DATA(LV_CHK_ORG)
      WHERE EKORG = @LV_EKORG.
    IF SY-SUBRC <> 0.
      RAISE EXCEPTION TYPE /IWBEP/CX_MGW_BUSI_EXCEPTION
        EXPORTING
          MESSAGE = |Purchasing Organization '{ LV_EKORG }' does not exist.|.
    ENDIF.
  ENDIF.

  "--- Validate Purchasing Group ---
  IF LV_EKGRP IS NOT INITIAL.
    SELECT SINGLE EKGRP FROM T024
      INTO @DATA(LV_CHK_GRP)
      WHERE EKGRP = @LV_EKGRP.
    IF SY-SUBRC <> 0.
      RAISE EXCEPTION TYPE /IWBEP/CX_MGW_BUSI_EXCEPTION
        EXPORTING
          MESSAGE = |Purchasing Group '{ LV_EKGRP }' does not exist.|.
    ENDIF.
  ENDIF.

  "--- SELECT JOIN (copy từ FORM fetch_data) ---
  SELECT EKKO~BUKRS,
         T001~BUTXT,
         EKKO~EBELN,
         EKKO~BEDAT,
         EKKO~EKORG,
         T024E~EKOTX,
         EKKO~EKGRP,
         T024~EKNAM,
         EKKO~LIFNR,
         LFA1~NAME1,
         EKKO~ERNAM,
         EKKO~WAERS,
         TCURT~LTEXT
    FROM EKKO
    LEFT OUTER JOIN T001  ON T001~BUKRS  = EKKO~BUKRS
    LEFT OUTER JOIN T024E ON T024E~EKORG = EKKO~EKORG
    LEFT OUTER JOIN T024  ON T024~EKGRP  = EKKO~EKGRP
    LEFT OUTER JOIN LFA1  ON LFA1~LIFNR  = EKKO~LIFNR
    LEFT OUTER JOIN TCURT ON TCURT~WAERS = EKKO~WAERS
                         AND TCURT~SPRAS = @SY-LANGU
    INTO TABLE @DATA(LT_RESULT)
    WHERE EKKO~BUKRS = @LV_BUKRS
      AND EKKO~EBELN = @LV_EBELN
      AND EKKO~EKORG = @LV_EKORG
      AND EKKO~EKGRP = @LV_EKGRP.

  "--- Map sang ET_ENTITYSET ---
  LOOP AT LT_RESULT INTO DATA(LS_ROW).
    CLEAR LS_HEADER.
    LS_HEADER-EBELN  = LS_ROW-EBELN.
    LS_HEADER-BUKRS  = LS_ROW-BUKRS.
    LS_HEADER-BUTXT  = LS_ROW-BUTXT.
    LS_HEADER-BEDAT  = LS_ROW-BEDAT.
    LS_HEADER-EKORG  = LS_ROW-EKORG.
    LS_HEADER-EKOTX  = LS_ROW-EKOTX.
    LS_HEADER-EKGRP  = LS_ROW-EKGRP.
    LS_HEADER-EKNAM  = LS_ROW-EKNAM.
    LS_HEADER-LIFNR  = LS_ROW-LIFNR.
    LS_HEADER-NAME1  = LS_ROW-NAME1.
    LS_HEADER-ERNAM  = LS_ROW-ERNAM.
    LS_HEADER-WAERS  = LS_ROW-WAERS.
    LS_HEADER-LTEXT  = LS_ROW-LTEXT.

    "--- Lấy tên người tạo (USR21 → ADRP) ---
    SELECT SINGLE PERSNUMBER FROM USR21
      INTO @DATA(LV_PERSNUMBER)
      WHERE BNAME = @LS_ROW-ERNAM.
    IF SY-SUBRC = 0.
      SELECT SINGLE NAME_FIRST, NAME_LAST FROM ADRP
        INTO (@DATA(LV_FIRST), @DATA(LV_LAST))
        WHERE PERSNUMBER = @LV_PERSNUMBER.
      LS_HEADER-NAMETEXT = |{ LV_FIRST } { LV_LAST }|.
    ELSE.
      LS_HEADER-NAMETEXT = LS_ROW-ERNAM.
    ENDIF.

    APPEND LS_HEADER TO ET_ENTITYSET.
  ENDLOOP.

ENDMETHOD.


METHOD PURCHASEORDERITE_GET_ENTITYSET.

  DATA: LS_ITEM  TYPE ZCL_ZPURCHASE_ORDER_01_MPC=>TS_PURCHASEORDERITEM,
        LV_EBELN TYPE EKPO-EBELN.

  LOOP AT IT_FILTER_SELECT_OPTIONS INTO DATA(LS_SEL).
    IF LS_SEL-PROPERTY = 'Ebeln'.
      LV_EBELN = LS_SEL-SELECT_OPTIONS[ 1 ]-LOW.
    ENDIF.
  ENDLOOP.

  SELECT EKPO~EBELN, EKPO~EBELP,
         EKPO~MATNR, MAKT~MAKTX,
         EKPO~MENGE, EKPO~MEINS,
         EKPO~NETPR
    FROM EKPO
    LEFT OUTER JOIN MAKT ON MAKT~MATNR = EKPO~MATNR
                        AND MAKT~SPRAS = @SY-LANGU
    INTO TABLE @DATA(LT_ITEMS)
    WHERE EKPO~EBELN = @LV_EBELN.

  LOOP AT LT_ITEMS INTO DATA(LS_ROW).
    CLEAR LS_ITEM.
    LS_ITEM-EBELN     = LS_ROW-EBELN.
    LS_ITEM-EBELP     = LS_ROW-EBELP.
    LS_ITEM-MATNR     = LS_ROW-MATNR.
    LS_ITEM-MAKTX     = LS_ROW-MAKTX.
    LS_ITEM-MENGE     = LS_ROW-MENGE.
    LS_ITEM-MEINS     = LS_ROW-MEINS.
    LS_ITEM-NETPR     = LS_ROW-NETPR.

    "--- Tính Unit Price ---
    IF LS_ROW-MENGE > 0.
      LS_ITEM-UNITPRICE = LS_ROW-NETPR / LS_ROW-MENGE.
    ENDIF.

    APPEND LS_ITEM TO ET_ENTITYSET.
  ENDLOOP.

ENDMETHOD.
ENDCLASS.
